### ISSUE TITLE
Update Password Tests

### ISSUE THREAD

**Issue by poppabear8883** [indiehd/web-api#57]
Need to create tests for the `updatePassword` method on the `UserController`

**Comment by cbj4074** [comment]
Fixed in a413b859633bd3940cd44564016a351fdd6bb93f

We ended-up eliminating the dedicated `updatePassword()` method in favor of handling the password just as we do any other user/account-related field.

Also, the password hashing is now handled in the UserRepository, rather than in the UserController.
